export const totalMovies: string[] = [
  "Frozen II",
  "Raya and the Last Dragon",
  "Encanto",
  "Turning Red",
  "Luca",
  "Strange World",
  "Cruella",
  "Lightyear",
  "The Little Mermaid",
  "Wish"
];

export const eventDefinitions: Record<string, string[]> = {
    "A character learns a valuable lesson": ["Frozen II", "Encanto", "Turning Red", "Luca", "Wish"],
    "A dance or ball scene": ["Encanto", "The Little Mermaid", "Wish"],
    "A funny animal sidekick": ["Frozen II", "Encanto", "Strange World", "Luca", "Wish"],
    "A magical item": ["Frozen II", "Raya and the Last Dragon", "Wish"],
    "A big feast or banquet": ["Encanto", "Luca"],
    "A secret identity revealed": ["Cruella", "Encanto"],
    "A powerful villain": ["Frozen II", "Strange World", "Lightyear", "Cruella"],
    "A heartwarming family reunion": ["Encanto", "Turning Red", "Wish"],
    "A character embarks on a quest": ["Frozen II", "Raya and the Last Dragon", "Lightyear"],
    "A water-based adventure": ["The Little Mermaid", "Luca", "Wish"],
    "A musical performance": ["Encanto", "The Little Mermaid", "Frozen II"],
    "A high-tech gadget": ["Strange World", "Lightyear"],
    "A magical curse": ["Frozen II", "Wish"],
    "A talking animal": ["Frozen II", "Strange World", "Luca", "Wish"],
    "A forbidden love": ["Luca", "The Little Mermaid"],
    "A kingdom in peril": ["Frozen II", "Raya and the Last Dragon", "Encanto"],
    "A comedic misunderstanding": ["Turning Red", "Luca", "Strange World"],
    "A sacrifice for a loved one": ["Wish", "Frozen II"],
    "A race against time": ["Lightyear", "Strange World", "Raya and the Last Dragon"],
    "A dramatic rescue": ["Encanto", "Lightyear", "The Little Mermaid"],
    "A magical transformation": ["Wish", "Frozen II", "The Little Mermaid"],
    "A mentor figure guides the hero": ["Raya and the Last Dragon", "Wish", "Turning Red"],
    "A heroic sacrifice": ["Lightyear", "Frozen II", "Strange World"],
    "A battle of wits": ["Encanto", "Cruella"],
    "A treasure hunt": ["Luca", "Raya and the Last Dragon"],
    "A comedic duo": ["Frozen II", "Strange World", "Luca"],
    "A celebration or festival": ["Encanto", "Luca"],
    "A tragic backstory revealed": ["Cruella", "Lightyear", "Encanto"],
    "A magical map": ["Raya and the Last Dragon", "Frozen II"],
    "A shipwreck scene": ["The Little Mermaid", "Strange World"],
    "A character overcomes self-doubt": ["Frozen II", "Turning Red", "Luca", "Wish"],
    "A surprising betrayal": ["Raya and the Last Dragon", "Cruella", "Lightyear"],
    "A dream sequence": ["Encanto", "Frozen II"],
    "A villain with a tragic past": ["Cruella", "Frozen II"],
    "A mysterious prophecy": ["Frozen II", "Wish"],
    "A magical forest": ["Frozen II", "Strange World"],
    "A thrilling chase scene": ["Lightyear", "Raya and the Last Dragon", "Turning Red"],
    "A character breaks tradition": ["Turning Red", "Encanto", "Luca"],
    "A heartfelt apology": ["Encanto", "Luca", "Turning Red"],
    "A magical creature": ["Frozen II", "Strange World", "Wish"],
    "A dangerous artifact": ["Raya and the Last Dragon", "Lightyear", "Wish"],
    "A character faces their fears": ["Frozen II", "Encanto", "Turning Red"],
    "A surprising ally": ["Strange World", "Lightyear", "Raya and the Last Dragon"],
    "A heartwarming romance": ["The Little Mermaid", "Luca"],
    "A message of forgiveness": ["Encanto", "Turning Red"],
    "A character finds their purpose": ["Wish", "Frozen II", "Encanto"],
    "A tragic loss": ["Cruella", "Lightyear", "Encanto"],
    "A character learns teamwork": ["Frozen II", "Turning Red", "Luca"],
    "A dramatic standoff": ["Lightyear", "Raya and the Last Dragon", "Strange World"],
    "A starry night scene": ["Wish", "Encanto", "Frozen II"],
    "A mysterious guide": ["Raya and the Last Dragon", "Wish", "Frozen II"],
    "A nostalgic flashback": ["Lightyear", "Encanto", "Cruella"],
    "A forbidden place explored": ["Frozen II", "The Little Mermaid"],
    "A thrilling flight": ["Lightyear", "Strange World"],
    "A powerful speech": ["Encanto", "Luca", "Turning Red"],
    "A symbolic object": ["Frozen II", "Wish", "Encanto"],
    "A dramatic storm": ["The Little Mermaid", "Frozen II", "Strange World"],
    "A rival turned friend": ["Lightyear", "Raya and the Last Dragon"],
    "A moment of redemption": ["Cruella", "Frozen II"],
    "A character defies expectations": ["Turning Red", "Luca", "Encanto"],
    "A vibrant market scene": ["Encanto", "Raya and the Last Dragon"],
    "A life-changing revelation": ["Frozen II", "Wish", "Lightyear"],
    "A journey to a far-off land": ["Raya and the Last Dragon", "Frozen II", "Lightyear"],
    "A competition or contest": ["Encanto", "Turning Red"],
    "A theme of self-acceptance": ["Turning Red", "Luca", "Encanto"],
    "A magical land": ["Wish", "Frozen II"],
    "A confrontation with destiny": ["Frozen II", "Wish"],
    "A test of courage": ["Strange World", "Lightyear", "Luca"],
    "A celebration of culture": ["Encanto", "Raya and the Last Dragon"],
    "A perilous journey": ["Frozen II", "Raya and the Last Dragon", "Wish"],
    "A pivotal choice": ["Lightyear", "Wish"],
    "A symbolic dance": ["The Little Mermaid", "Encanto"],
    "A majestic castle": ["Frozen II", "Wish", "Raya and the Last Dragon"],
    "A bond between siblings": ["Encanto", "Frozen II"],
    "A theme of hope": ["Wish", "Frozen II"],
    "A daring escape": ["Raya and the Last Dragon", "Lightyear", "Strange World"],
    "A spectacular fireworks display": ["Encanto", "Frozen II"],
    "A message of resilience": ["Wish", "Turning Red"],
    "A character faces the unknown": ["Frozen II", "Strange World"],
    "A theme of forgiveness": ["Encanto", "Turning Red"],
    "A symbol of unity": ["Wish", "Encanto"],
    "A world-changing event": ["Strange World", "Lightyear"],
    "A surprising mentor": ["Raya and the Last Dragon", "Turning Red"],
    "A heartfelt farewell": ["Encanto", "Frozen II"],
    "A secret lair": ["Strange World", "Lightyear"],
    "A theme of redemption": ["Cruella", "Encanto"],
    "A scenic beach setting": ["The Little Mermaid", "Luca"],
    "A magical tree": ["Frozen II", "Wish"],
    "A character reconnects with nature": ["Luca", "Turning Red", "Wish"],
    "A whimsical musical number": ["Encanto", "The Little Mermaid"],
    "A daring leap of faith": ["Frozen II", "Luca"],
    "A bond with a mystical animal": ["Strange World", "Wish"],
    "A challenge of loyalty": ["Encanto", "Raya and the Last Dragon"],
    "A heartfelt promise": ["Frozen II", "Encanto", "Turning Red"],
    "A futuristic cityscape": ["Lightyear", "Strange World"],
    "A daring heist": ["Cruella", "Raya and the Last Dragon"],
    "A reunion of old friends": ["Frozen II", "Encanto"],
    "A theme of justice": ["Encanto", "Raya and the Last Dragon"],
    "A moment of levity in danger": ["Frozen II", "Strange World", "Lightyear"],
    "A heartfelt confession": ["Turning Red", "Encanto", "Wish"]
}; 